version: '3.8'

services:
  reddit-sentiment-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT:-RedditStockSentiment/1.0}
      - MIN_COMMENT_KARMA=${MIN_COMMENT_KARMA:-100}
      - MIN_ACCOUNT_AGE_DAYS=${MIN_ACCOUNT_AGE_DAYS:-30}
      - SENTIMENT_THRESHOLD=${SENTIMENT_THRESHOLD:-0.15}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./tickers.json:/app/tickers.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s